/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiEndpointsPanel: typeof import('./src/components/ApiEndpointsPanel.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    EntityCard: typeof import('./src/components/EntityCard.vue')['default']
    EntityDesigner: typeof import('./src/components/EntityDesigner.vue')['default']
    EntityRelationshipGraph: typeof import('./src/components/EntityRelationshipGraph.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
